/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const getViewer: typeof import('../src/core/viewerStore/index')['getViewer']
  const isArray: typeof import('../src/shared/general')['isArray']
  const isDate: typeof import('../src/shared/general')['isDate']
  const isFunction: typeof import('../src/shared/general')['isFunction']
  const isMap: typeof import('../src/shared/general')['isMap']
  const isObject: typeof import('../src/shared/general')['isObject']
  const isPromise: typeof import('../src/shared/general')['isPromise']
  const isRegExp: typeof import('../src/shared/general')['isRegExp']
  const isSet: typeof import('../src/shared/general')['isSet']
  const isString: typeof import('../src/shared/general')['isString']
  const isSymbol: typeof import('../src/shared/general')['isSymbol']
  const isUndefined: typeof import('../src/shared/general')['isUndefined']
  const setViewer: typeof import('../src/core/viewerStore/index')['setViewer']
  const toCartesian3: typeof import('../src/shared/coordinate')['toCartesian3']
  const toTypeString: typeof import('../src/shared/general')['toTypeString']
  const useViewerProvider: typeof import('../src/core/viewerStore/index')['useViewerProvider']
}
