/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const afterAll: typeof import('vitest')['afterAll']
  const afterEach: typeof import('vitest')['afterEach']
  const assert: typeof import('vitest')['assert']
  const beforeAll: typeof import('vitest')['beforeAll']
  const beforeEach: typeof import('vitest')['beforeEach']
  const chai: typeof import('vitest')['chai']
  const describe: typeof import('vitest')['describe']
  const expect: typeof import('vitest')['expect']
  const getViewer: typeof import('../src/core/viewerStore/index')['getViewer']
  const isArray: typeof import('../src/shared/general')['isArray']
  const isDate: typeof import('../src/shared/general')['isDate']
  const isFunction: typeof import('../src/shared/general')['isFunction']
  const isMap: typeof import('../src/shared/general')['isMap']
  const isObject: typeof import('../src/shared/general')['isObject']
  const isPromise: typeof import('../src/shared/general')['isPromise']
  const isRegExp: typeof import('../src/shared/general')['isRegExp']
  const isSet: typeof import('../src/shared/general')['isSet']
  const isString: typeof import('../src/shared/general')['isString']
  const isSymbol: typeof import('../src/shared/general')['isSymbol']
  const it: typeof import('vitest')['it']
  const setViewer: typeof import('../src/core/viewerStore/index')['setViewer']
  const suite: typeof import('vitest')['suite']
  const test: typeof import('vitest')['test']
  const toCartesian3: typeof import('../src/shared/coordinate')['toCartesian3']
  const toTypeString: typeof import('../src/shared/general')['toTypeString']
  const useViewerProvider: typeof import('../src/core/viewerStore/index')['useViewerProvider']
  const vi: typeof import('vitest')['vi']
  const vitest: typeof import('vitest')['vitest']
}
