// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = ["defineColor","editEntity","loadGeojson","projectionPosition","syncEntityCollection","toCartesian3","toCoordinates","useEntityCollection","useEventHandler","useFlyToArea","useGlobePick","useLocated","useMeasure","useMoveByKeyboard","usePointerPosition","usePoints","usePrimitiveCollection","useTimeline","useViewer","useViewerProvider"] as const

/**
 * @returns Call in `imports` option of `unplugin-auto-import`.
 */
export default function autoImport(map?: Partial<{ [K in typeof __UnExportList[number]]: string }>): Record<string, (string | [string, string])[]> {
  return {
    'cesium-use': __UnExportList.map(v => map && map[v] ? [v, map[v]] as [string, string] : v),
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
